### PR TITLE
1st argument changes, remove "path" and "url" options, bug fixes

### PR DESCRIPTION
**Pull request by alex-cory**
**Summary**
1. this removes the `path` and `url` fields in exchange for the 1st argument handling both. https://github.com/ava/use-http/issues/247
    BREAKING CHANGE 🚨
```js
useFetch('/path')
// AND
useFetch('https://overwrite-global-url.com')
```
2. Fixes issue when overwriting global options, it changes for every instance of useFetch. https://github.com/ava/use-http/issues/250

3. fixes the pagination issue here https://github.com/ava/use-http/issues/237 but might not fix the `loading` bug.

4. small bug fix with `responseType`

**Todos**
1. need more tests
    - test for `useFetch('path')` without the `/` in the path (might be fine with the current tests)
2. codesandbox for conditional auto-managed state
3. update youtube video for `path` to explain how the new way works
4. draft a release explaining the breaking changes
5. update all codesandboxes using `path` and `url` options. I think it's just [this one](https://codesandbox.io/s/usefetch-provider-requestresponse-interceptors-s1lex?file=/src/index.js) and [this one](https://codesandbox.io/s/usefetch-provider-pagination-exttg?file=/src/index.js)

### CODE REVIEW

**Comment by JonKrone** [comment]
Hey Alex!

Thanks for your work on this! I used this library for a toy project over the weekend and it was fairly seamless.

I saw in the issue thread that sparked this your consideration of a `skip` vs a null `path`. Can you share your reasoning for going with the `path` approach?

I have a slight preference for a `skip` option to avoid overriding the `path` parameter, though I understand that either option has some mental overhead for the library.

**Comment by alex-cory** [comment]
@JonKrone I've been doing a lot of research on all the various patterns people use. It seems [swr](https://github.com/zeit/swr#conditional-fetching) and [react-query](https://github.com/tannerlinsley/react-query#pass-a-falsy-query-key) most libraries are blocking fetches with a `null` or falsy value. Looks like [@apollo/react-hooks](https://stackoverflow.com/a/59489673/2782583) is using the `skip` option. I am open to the `skip` option. I wanna get some more feedback and I'll get back to you.

**Comment by alex-cory** [comment]
@JonKrone After looking at it more, seems like [@apollo/react-hooks](https://www.npmjs.com/package/@apollo/react-hooks) has significantly more downloads and significantly more people using it. I might do the `skip` option.

**Comment by alex-cory** [comment]
I wish there was a way to crowd source people's opinions on this.

**Comment by alex-cory** [comment]
I found a way to crowdsource people's opinions on reddit. See the [poll here](https://www.reddit.com/r/reactjs/comments/g69y5p/conditional_react_hook_data_fetching_syntax/) on whether to use `skip` option or `null` value.

**Comment by alex-cory** [comment]
Going to let more people vote before adding conditional auto-managed state. Gonna get these fixes in now though.

**Pull request merged**
