### PR TITLE
Fix ReqBase<TData>['error'] type

### PR DESCRIPTION
**Pull request by alexburner**
It is currently marked as always having a value. But this is not true, its value is `undefined` when the request is either loading or successful. 

This means that checking whether the `error` property has a value will trigger `@typescript-eslint/strict-boolean-expressions`

ESLint rule doc: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md

Example playground: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAVwM4FMBiKYGMAWcBmUEIcA5MigLQ4wxikBQDWEAdkvAN5wA2EAhgBNgrAOYAaOCihEokwfxj84AXzgBeRKgzYcAClI06SAFwB6MygAe-cDxQA6FiDP8wwUpM4rJAbQC6AJRMwPhwetKygXCcDHDxcCzsEPYOfKIGACo4KHAwAJ5gKEhwSPz5eTjAJUnCMMBscADuwDw8cPw8TeUlAEa5MFAIKKTBKgxAA

### CODE REVIEW

**Comment by alex-cory** [comment]
Breaking in circleci otherwise I'd merge. Fix this, then will merge.

**Comment by ZebulanStanphill** [comment]
I made a PR for this PR (heh) to fix the issues found by circleci: https://github.com/alexburner/use-http/pull/1

**Comment by alexburner** [comment]
I won't say no to free code, thanks @ZebulanStanphill

**Comment by ZebulanStanphill** [comment]
The fixes made some tests fail TypeScript type analysis since the error objects are now known to possibly be undefined, so I've made a PR to update those tests to use optional chaining.

**Comment by alex-cory** [comment]
The [circleci tests](https://app.circleci.com/pipelines/github/ava/use-http/1153/workflows/93a08372-0e8e-49e7-bf2b-192033f7f7bd/jobs/1177/parallel-runs/0/steps/0-105) are still breaking. Once these are fixed I will merge. Thanks for the contributions!

```sh
#!/bin/bash -eo pipefail
yarn test
yarn run v1.22.0
$ yarn test:browser && yarn test:server
$ yarn tsc && jest -c ./config/jest.config.js --env=jsdom
$ tsc -p . --noEmit && tsc -p ./src/__tests__
src/__tests__/useFetch.test.tsx:168:12 - error TS2532: Object is possibly 'undefined'.

168     expect(result.current.error.name).toBe('FetchError')
               ~~~~~~~~~~~~~~~~~~~~

src/__tests__/useFetch.test.tsx:353:12 - error TS2532: Object is possibly 'undefined'.

353     expect(result.current.error.name).toBe('AbortError')
               ~~~~~~~~~~~~~~~~~~~~

src/__tests__/useFetch.test.tsx:354:12 - error TS2532: Object is possibly 'undefined'.

354     expect(result.current.error.message).toBe('Timeout Error')
               ~~~~~~~~~~~~~~~~~~~~

src/__tests__/useFetch.test.tsx:386:12 - error TS2532: Object is possibly 'undefined'.

386     expect(result.current.error.name).toBe('AbortError')
               ~~~~~~~~~~~~~~~~~~~~

src/__tests__/useFetch.test.tsx:387:12 - error TS2532: Object is possibly 'undefined'.

387     expect(result.current.error.message).toBe('Timeout Error')
               ~~~~~~~~~~~~~~~~~~~~


Found 5 errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by alexburner** [comment]
Thanks again @ZebulanStanphill — these nesting PRs are continually hilarious. To streamline the hilarity, I've invited you to be a collaborator on my fork, you're clearly more productive than me

**Comment by alexburner** [comment]
@alex-cory it looks like Zebulan has fixed those failing tests now

**Pull request merged**
