### PR TITLE
Check for FormData before checking for object when preparing body

### PR DESCRIPTION
**Pull request by sbichenko**

### CODE REVIEW

**Comment by alex-cory** [comment]
Did you run the tests? I forgot to put that in the notes for contributing.
```sh
yarn test:browser:watch
```

**Comment by sbichenko** [comment]
I did run the tests. One test fails before and after the change that I made:

```
● useFetch - BROWSER - persistence › should fetch again after 24h
```

**Comment by alex-cory** [comment]
Hm... did you checkout master, pull, and rerun the tests to see if it was failing before?

**Comment by sbichenko** [comment]
Yes I did. Just did `git pull` and rerun them again on `master` and got the same failing test.

**Comment by alex-cory** [comment]
Weird. I'll check out your branch and see if I can reproduce. My master is working.

**Comment by alex-cory** [comment]
Hm... I'll check this in the morning. It's almost 3am here.
image

**Comment by alex-cory** [comment]
I'm having trouble understanding why the circleci tests are running on this PR. I'm going to merge this and if the builds fail, I'll rollback and take a closer look.

**Comment by alex-cory** [comment]
Seems all the tests are passing. This is published in `v1.0.7`

**Pull request merged**
