### PR TITLE
Provide original request in response interceptor (#319)

### PR DESCRIPTION
**Pull request by nebarf**
https://github.com/ava/use-http/issues/319

### CODE REVIEW

**Comment by juandopazo** [comment]
I was just looking into this and considering opening a pull request. I think the project maintainers would appreciate adding coverage to the unit tests. Similar to https://github.com/ava/use-http/blob/master/src/__tests__/useFetch.test.tsx#L594-L602. I'm happy to open a PR against your branch if you want me to.

**Comment by nebarf** [comment]
@juandopazo Sure, feel free to open a PR against my master branch with missing test and docs. Thanks

**Comment by nebarf** [comment]
What about adding the same capabilities in `onError` and `onAbort` hooks?

**Comment by nebarf** [comment]
@alex-cory Can u take a look at it? Thanks.

**Comment by alex-cory** [comment]
Looking!

**Pull request merged**
